version: "3.8"
services:
  postgres:
    image: 
    container_name: 
    restart: 
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - 
    volumes:
      - 

volumes:
  postgres_data:
